"""empty message

Revision ID: 064f14e5ec75
Revises: b25cf9bc1914
Create Date: 2024-03-12 15:25:04.828133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064f14e5ec75'
down_revision = 'b25cf9bc1914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
