"""empty message

Revision ID: 065233b63262
Revises: 39fffb3bf13e
Create Date: 2024-03-19 11:07:46.659145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065233b63262'
down_revision = '39fffb3bf13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_liked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_column('is_liked')

    # ### end Alembic commands ###
