"""empty message

Revision ID: 39fffb3bf13e
Revises: b62511a7cfcd
Create Date: 2024-03-19 10:42:50.450527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fffb3bf13e'
down_revision = 'b62511a7cfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
