"""empty message

Revision ID: 5fb7db5be2d1
Revises: c7f1cab727b4
Create Date: 2024-03-19 08:29:11.664837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb7db5be2d1'
down_revision = 'c7f1cab727b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('likes_article_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'], ondelete='cascade')
        batch_op.drop_column('article_id')

    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.alter_column('is_favorited',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.alter_column('is_favorited',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_article_id_fkey', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
