"""empty message

Revision ID: b59aef5961b6
Revises: 064f14e5ec75
Create Date: 2024-03-16 16:14:31.490218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b59aef5961b6'
down_revision = '064f14e5ec75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('likes')
    op.drop_table('comment')
    op.drop_table('user_favorite')
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('articles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='articles_pkey'),
    sa.UniqueConstraint('url', name='articles_url_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_favorite',
    sa.Column('article_being_favorited_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_favorited_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_being_favorited_id'], ['users.id'], name='user_favorite_article_being_favorited_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_favorited_id'], ['users.id'], name='user_favorite_user_favorited_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_being_favorited_id', 'user_favorited_id', name='user_favorite_pkey')
    )
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('comment_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=140), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='comment_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='likes_comment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='likes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='likes_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
