"""empty message

Revision ID: b62511a7cfcd
Revises: 5e9348bd698b
Create Date: 2024-03-19 09:18:41.269709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62511a7cfcd'
down_revision = '5e9348bd698b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.drop_table('user_favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite',
    sa.Column('article_being_favorited_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_favorited', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_being_favorited_id'], ['articles.id'], name='user_favorite_article_being_favorited_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_favorite_user_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
