"""empty message

Revision ID: c7f1cab727b4
Revises: 69474736c15e
Create Date: 2024-03-19 07:49:16.208199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f1cab727b4'
down_revision = '69474736c15e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorited', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite', schema=None) as batch_op:
        batch_op.drop_column('is_favorited')

    # ### end Alembic commands ###
